spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=atquilDB;encrypt=false;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: dpk
    password: 1402

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  config: classpath:log4j2.xml
  level:
    org.springframework.security: trace
    atquil.jwt_oauth2.logClass: debug

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem

server:
  tomcat:
    max-swallow-size: -1
  port: 8080
  address: 0.0.0.0

servlet:
  multipart:
    max-file-size: 50MB
    max-request-size: 50MB
    enabled: true
